# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      # Backend Setup
      - name: Use Node.js ${{ matrix.node-version }} for backend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          working-directory: ./backend

      - name: Install dependencies for backend
        run: npm ci
        working-directory: ./backend

      - name: Build backend
        run: npm run build --if-present
        working-directory: ./backend

      - name: Test backend
        run: npm test
        working-directory: ./backend

      # Frontend Setup
      - name: Use Node.js ${{ matrix.node-version }} for frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          working-directory: ./frontend

      - name: Install dependencies for frontend
        run: npm ci
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build --if-present
        working-directory: ./frontend

      - name: Test frontend
        run: npm test
        working-directory: ./frontend
